image:
  file: .gitpod.Dockerfile
  
ports:
- port: 8080
  onOpen: open-preview

tasks:
- before: >
    echo "starting..."
  init: >
    cd rxdb
    npm install
    npm run build
    cd examples/vue
    npm run preinstall && npm install
  command: >
    npm start
