image:
  file: .gitpod.Dockerfile
  
ports:
- port: 8080
  onOpen: open-preview

tasks:
  - init: |
      cd rxdb
      npm install
      npm install
      cd examples/vue
      npm run preinstall
      npm install
    command: |
      npm start
  - command: gp await-port 8080 && gp preview "$(gp url 8080)/"
